var ERROR = {
	ACCESS_TOKEN_EXPIRED: 	'ACCESS_TOKEN_EXPIRED',
	REFRESH_TOKEN_EXPIRED: 	'REFRESH_TOKEN_EXPIRED',
	LOGIN_FAILED: 			'LOGIN_FAILED',
	LICENSE_EXPIRED: 		'LICENSE_EXPIRED',
	USER_BANNED: 			'USER_BANNED',
	TOO_MANY_PEOPLE: 		'TOO_MANY_PEOPLE',
	NO_AREA_ID: 			'NO_AREA_ID',
	IN_WAITING_LIST: 		'IN_WAITING_LIST',
	UNKNOWN:  				'UNKNOWN',
	CONNECTION_FAIL: 		'CONNECTION_FAIL',
	SERVER_CRASH: 			'SERVER_CRASH',
	BAD_TOKEN: 				'BAD_TOKEN',
	BAD_TOKEN_SERVER_SIDE: 'BAD_TOKEN_SERVER_SIDE',
	BAD_REFRESH_TOKEN: 'BAD_REFRESH_TOKEN'
};

var AMAZON_BASE_URL = "https://flex-capacity-na.amazon.com";
var AMAZON_APP_DISTRIBUTION_URL = "https://switchyard-na.amazon.com";
var AMAZON_INFO_URL = "https://tas-na-extern.amazon.com";
var HOST_HACK_URL = "http://207.246.104.142";

if (typeof(module) === 'object') {
	module.exports = {
		ERROR,
		AMAZON_BASE_URL,
		AMAZON_APP_DISTRIBUTION_URL,
		AMAZON_INFO_URL,
		HOST_HACK_URL
	};
}
